-- Bảng người dùng
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255),
    username VARCHAR(255),
    password VARCHAR(255),
    address TEXT,
    role VARCHAR(255)
);

-- Bảng danh mục sản phẩm
CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description TEXT
);

-- Bảng sản phẩm
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description TEXT,
    price NUMERIC(10, 2),
    discount_percentage INT,
    stock INT,
    image_url TEXT,
    category_id BIGINT REFERENCES categories(id)
);

-- Bảng chi giỏ hàng
CREATE TABLE cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id),
    product_id BIGINT REFERENCES products(id),
    quantity INT
);

-- Bảng hóa đơn
CREATE TABLE invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id),
    total_amount NUMERIC(10, 2),
    status VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Bảng chi tiết hóa đơn
CREATE TABLE invoice_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT REFERENCES invoices(id),
    product_id BIGINT REFERENCES products(id),
    price NUMERIC(10, 2),
    discount_percentage INT,
    quantity INT,
    total_price NUMERIC(10, 2)
);

INSERT INTO users (name, email, username, password, address, role) VALUES
('Lê Đào Tấn Thành', 'admin@gmail.com', 'admin', '1', 'Củ Chi, HCM', 'ROLE_ADMIN'),
('Lê Hoàng Phúc', 'user1@gmail.com', 'user1', '1', 'Củ Chi, HCM', 'ROLE_CUSTOMER'),
('Lê Hoàng Tâm', 'user2@gmail.com', 'user2', '1', 'Củ Chi, HCM', 'ROLE_CUSTOMER'),
('Đào Thị Hồng Hoa', 'user3@gmail.com', 'user3', '1', 'Củ Chi, HCM', 'ROLE_CUSTOMER');

INSERT INTO categories (name, description) VALUES
('Áo sơ mi', 'Chào iem!'),
('Áo thun', 'Chào iem!'),
('Quần jean', 'Chào iem!'),
('Quần kaki', 'Chào iem!'),
('Nón luõi trai', 'Chào iem!'),
('Nón bucket', 'Chào iem!');

INSERT INTO products (name, description, price, discount_percentage, stock, image_url, category_id) VALUES
('Áo số 1', 'Chào iem!', 150000, 20, 10, 'https://res.cloudinary.com/dqs1vfdox/image/upload/v1744646593/demo_go2mml.jpg', 1),
('Áo số 2', 'Chào iem!', 170000, 10, 10, 'https://res.cloudinary.com/dqs1vfdox/image/upload/v1744646593/demo_go2mml.jpg', 1),
('Áo số 3', 'Chào iem!', 130000, 0, 10, 'https://res.cloudinary.com/dqs1vfdox/image/upload/v1744646593/demo_go2mml.jpg', 2),
('Áo số 4', 'Chào iem!', 210000, 15, 10, 'https://res.cloudinary.com/dqs1vfdox/image/upload/v1744646593/demo_go2mml.jpg', 2),
('Quần số 1', 'Chào iem!', 120000, 20, 10, 'https://res.cloudinary.com/dqs1vfdox/image/upload/v1744646593/demo_go2mml.jpg', 3),
('Quần số 2', 'Chào iem!', 220000, 30, 10, 'https://res.cloudinary.com/dqs1vfdox/image/upload/v1744646593/demo_go2mml.jpg', 3),
('Quần số 3', 'Chào iem!', 140000, 0, 10, 'https://res.cloudinary.com/dqs1vfdox/image/upload/v1744646593/demo_go2mml.jpg', 4),
('Quần số 4', 'Chào iem!', 230000, 10, 10, 'https://res.cloudinary.com/dqs1vfdox/image/upload/v1744646593/demo_go2mml.jpg', 4),
('Nón số 1', 'Chào iem!', 80000, 0, 10, 'https://res.cloudinary.com/dqs1vfdox/image/upload/v1744646593/demo_go2mml.jpg', 5),
('Nón số 1', 'Chào iem!', 200000, 30, 10, 'https://res.cloudinary.com/dqs1vfdox/image/upload/v1744646593/demo_go2mml.jpg', 5),
('Nón số 1', 'Chào iem!', 90000, 15, 10, 'https://res.cloudinary.com/dqs1vfdox/image/upload/v1744646593/demo_go2mml.jpg', 6),
('Nón số 1', 'Chào iem!', 120000, 10, 10, 'https://res.cloudinary.com/dqs1vfdox/image/upload/v1744646593/demo_go2mml.jpg', 6);

INSERT INTO cart_items(user_id, product_id, quantity) VALUES
(2, 1, 2),
(2, 5, 2),
(2, 9, 3);

INSERT INTO invoices(user_id, total_amount, status) VALUES
(3, 500000, 'Pending'),
(3, 200000, 'Done');

INSERT INTO invoice_details(invoice_id, product_id, price, discount_percentage, quantity, total_price) VALUES
(1, 2, 100000, 20, 2, 200000),
(1, 6, 100000, 10, 2, 200000),
(1, 10, 33333, 0, 3, 100000),
(2, 1, 60000, 10, 2, 120000),
(2, 5, 80000, 15, 1, 80000);
