-- Bảng người dùng
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullname VARCHAR(100),
    email VARCHAR(255) UNIQUE NOT NULL,
    username VARCHAR(255) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    address TEXT NOT NULL,
    role_name VARCHAR(50) NOT NULL CHECK (role_name IN ('ADMIN', 'CUSTOMER')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO users (fullname, email, username, password_hash, address, role_name) VALUES
('Lê Đào Tấn Thành', 'admin@gmail.com', 'admin', '1', 'Củ Chi, HCM', 'ADMIN'),
('Lê Hoàng Phúc', 'user1@gmail.com', 'user1', '1', 'Củ Chi, HCM', 'CUSTOMER'),
('Lê Hoàng Tâm', 'user2@gmail.com', 'user2', '1', 'Củ Chi, HCM', 'CUSTOMER'),
('Đào Thị Hồng Hoa', 'user3@gmail.com', 'user3', '1', 'Củ Chi, HCM', 'CUSTOMER');

-- Bảng danh mục sản phẩm
CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO categories (name, description) VALUES
('Áo sơ mi', 'Mô tả ...'),
('Áo thun', 'Mô tả ...'),
('Quần jean', 'Mô tả ...'),
('Quần kaki', 'Mô tả ...'),
('Nón luõi trai', 'Mô tả ...'),
('Nón bucket', 'Mô tả ...');

-- Bảng sản phẩm
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    price NUMERIC(10, 2) NOT NULL CHECK (price > 0),
    discount_percentage INT NOT NULL CHECK (discount_percentage >= 0 AND discount_percentage <= 100),
    stock INT NOT NULL CHECK (stock >= 0),
    image_url TEXT NOT NULL,
    category_id BIGINT NOT NULL REFERENCES categories(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
INSERT INTO products (name, description, price, discount_percentage, stock, image_url, category_id) VALUES
('Áo số 1', 'Mô tả ...', 150000, 20, 10, 'https://res.cloudinary.com/dqs1vfdox/image/upload/v1744646593/demo_go2mml.jpg', 1),
('Áo số 2', 'Mô tả ...', 170000, 10, 10, 'https://res.cloudinary.com/dqs1vfdox/image/upload/v1744646593/demo_go2mml.jpg', 1),
('Áo số 3', 'Mô tả ...', 130000, 0, 10, 'https://res.cloudinary.com/dqs1vfdox/image/upload/v1744646593/demo_go2mml.jpg', 2),
('Áo số 4', 'Mô tả ...', 210000, 15, 10, 'https://res.cloudinary.com/dqs1vfdox/image/upload/v1744646593/demo_go2mml.jpg', 2),
('Quần số 1', 'Mô tả ...', 120000, 20, 10, 'https://res.cloudinary.com/dqs1vfdox/image/upload/v1744646593/demo_go2mml.jpg', 3),
('Quần số 2', 'Mô tả ...', 220000, 30, 10, 'https://res.cloudinary.com/dqs1vfdox/image/upload/v1744646593/demo_go2mml.jpg', 3),
('Quần số 3', 'Mô tả ...', 140000, 0, 10, 'https://res.cloudinary.com/dqs1vfdox/image/upload/v1744646593/demo_go2mml.jpg', 4),
('Quần số 4', 'Mô tả ...', 230000, 10, 10, 'https://res.cloudinary.com/dqs1vfdox/image/upload/v1744646593/demo_go2mml.jpg', 4),
('Nón số 1', 'Mô tả ...', 80000, 0, 10, 'https://res.cloudinary.com/dqs1vfdox/image/upload/v1744646593/demo_go2mml.jpg', 5),
('Nón số 1', 'Mô tả ...', 200000, 30, 10, 'https://res.cloudinary.com/dqs1vfdox/image/upload/v1744646593/demo_go2mml.jpg', 5),
('Nón số 1', 'Mô tả ...', 90000, 15, 10, 'https://res.cloudinary.com/dqs1vfdox/image/upload/v1744646593/demo_go2mml.jpg', 6),
('Nón số 1', 'Mô tả ...', 120000, 10, 10, 'https://res.cloudinary.com/dqs1vfdox/image/upload/v1744646593/demo_go2mml.jpg', 6);

-- Bảng giỏ hàng
CREATE TABLE carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
INSERT INTO carts(user_id) VALUES
(2),
(3),
(4);

-- Bảng chi tiết mặt hàng trong giỏ hàng
CREATE TABLE cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id BIGINT NOT NULL REFERENCES carts(id),
    product_id BIGINT NOT NULL REFERENCES products(id),
    quantity INT NOT NULL CHECK (quantity > 0),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
INSERT INTO cart_items(cart_id, product_id, quantity) VALUES
(2, 1, 2),
(2, 5, 2),
(2, 9, 3);

-- Bảng hóa đơn
CREATE TABLE invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    total_amount NUMERIC(10, 2) NOT NULL CHECK (total_amount > 0),
    status VARCHAR(50) NOT NULL CHECK (status IN ('PENDING', 'DONE', 'CANCELLED')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
(3, 500000, 'PENDING'),
(3, 200000, 'DONE');

-- Bảng chi tiết hóa đơn
CREATE TABLE invoice_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL REFERENCES invoices(id),
    product_id BIGINT NOT NULL REFERENCES products(id),
    price NUMERIC(10, 2) NOT NULL CHECK (price > 0),
    discount_percentage INT NOT NULL CHECK (discount_percentage >= 0 AND discount_percentage <= 100),
    quantity INT NOT NULL CHECK (quantity > 0),
    total_price NUMERIC(10, 2) NOT NULL CHECK (total_price > 0),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
INSERT INTO invoice_details(invoice_id, product_id, price, discount_percentage, quantity, total_price) VALUES
(1, 2, 100000, 20, 2, 200000),
(1, 6, 100000, 10, 2, 200000),
(1, 10, 33333, 0, 3, 100000),
(2, 1, 60000, 10, 2, 120000),
(2, 5, 80000, 15, 1, 80000);